# Generated by Django 2.0.5 on 2018-05-19 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_sahip'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='plaka',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
